spring.application.name=wol-bot-native
spring.threads.virtual.enabled=true

management.endpoints.web.exposure.include=health,metrics,threaddump

wol.bot.token=${BOT_TOKEN}
wol.valid.use.name=${VALID_USER_NAME}
wol.mac.address=${MAC_ADDRESS}
wol.broadcast.address=${BROADCAST_ADDRESS}
wol.broadcast.port=${BROADCAST_PORT:9}
